/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oracle.assignmnet;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
        System.out.println("gradle Configuration successful");
    }
}
